version: '3.4'

services:
  livraria-lello-dependencies:
    image: jwilder/dockerize
    depends_on:
      - livraria-lello-mysql
  livraria-lello-app:
    build:
      context: .
      target: livraria-lello
    ports:
      - 8080:8080
    env_file:
      - docker.env

  livraria-lello-mysql:
    build:
      context: docker/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root